//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EComWFE.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.HelloServiceSoap")]
    public interface HelloServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        EComWFE.ServiceReference1.HelloWorldResponse HelloWorld(EComWFE.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<EComWFE.ServiceReference1.HelloWorldResponse> HelloWorldAsync(EComWFE.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetMentorResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMentor", ReplyAction="*")]
        EComWFE.ServiceReference1.GetMentorResponse GetMentor(EComWFE.ServiceReference1.GetMentorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMentor", ReplyAction="*")]
        System.Threading.Tasks.Task<EComWFE.ServiceReference1.GetMentorResponse> GetMentorAsync(EComWFE.ServiceReference1.GetMentorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNextTestDay", ReplyAction="*")]
        System.DateTime GetNextTestDay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNextTestDay", ReplyAction="*")]
        System.Threading.Tasks.Task<System.DateTime> GetNextTestDayAsync();
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validate", ReplyAction="*")]
        EComWFE.ServiceReference1.ValidateResponse Validate(EComWFE.ServiceReference1.ValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Validate", ReplyAction="*")]
        System.Threading.Tasks.Task<EComWFE.ServiceReference1.ValidateResponse> ValidateAsync(EComWFE.ServiceReference1.ValidateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public EComWFE.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(EComWFE.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public EComWFE.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(EComWFE.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMentorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMentor", Namespace="http://tempuri.org/", Order=0)]
        public EComWFE.ServiceReference1.GetMentorRequestBody Body;
        
        public GetMentorRequest() {
        }
        
        public GetMentorRequest(EComWFE.ServiceReference1.GetMentorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMentorRequestBody {
        
        public GetMentorRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMentorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMentorResponse", Namespace="http://tempuri.org/", Order=0)]
        public EComWFE.ServiceReference1.GetMentorResponseBody Body;
        
        public GetMentorResponse() {
        }
        
        public GetMentorResponse(EComWFE.ServiceReference1.GetMentorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMentorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMentorResult;
        
        public GetMentorResponseBody() {
        }
        
        public GetMentorResponseBody(string GetMentorResult) {
            this.GetMentorResult = GetMentorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validate", Namespace="http://tempuri.org/", Order=0)]
        public EComWFE.ServiceReference1.ValidateRequestBody Body;
        
        public ValidateRequest() {
        }
        
        public ValidateRequest(EComWFE.ServiceReference1.ValidateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidateRequestBody() {
        }
        
        public ValidateRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateResponse", Namespace="http://tempuri.org/", Order=0)]
        public EComWFE.ServiceReference1.ValidateResponseBody Body;
        
        public ValidateResponse() {
        }
        
        public ValidateResponse(EComWFE.ServiceReference1.ValidateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateResult;
        
        public ValidateResponseBody() {
        }
        
        public ValidateResponseBody(bool ValidateResult) {
            this.ValidateResult = ValidateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloServiceSoapChannel : EComWFE.ServiceReference1.HelloServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloServiceSoapClient : System.ServiceModel.ClientBase<EComWFE.ServiceReference1.HelloServiceSoap>, EComWFE.ServiceReference1.HelloServiceSoap {
        
        public HelloServiceSoapClient() {
        }
        
        public HelloServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EComWFE.ServiceReference1.HelloWorldResponse EComWFE.ServiceReference1.HelloServiceSoap.HelloWorld(EComWFE.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            EComWFE.ServiceReference1.HelloWorldRequest inValue = new EComWFE.ServiceReference1.HelloWorldRequest();
            inValue.Body = new EComWFE.ServiceReference1.HelloWorldRequestBody();
            EComWFE.ServiceReference1.HelloWorldResponse retVal = ((EComWFE.ServiceReference1.HelloServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EComWFE.ServiceReference1.HelloWorldResponse> EComWFE.ServiceReference1.HelloServiceSoap.HelloWorldAsync(EComWFE.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<EComWFE.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            EComWFE.ServiceReference1.HelloWorldRequest inValue = new EComWFE.ServiceReference1.HelloWorldRequest();
            inValue.Body = new EComWFE.ServiceReference1.HelloWorldRequestBody();
            return ((EComWFE.ServiceReference1.HelloServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EComWFE.ServiceReference1.GetMentorResponse EComWFE.ServiceReference1.HelloServiceSoap.GetMentor(EComWFE.ServiceReference1.GetMentorRequest request) {
            return base.Channel.GetMentor(request);
        }
        
        public string GetMentor() {
            EComWFE.ServiceReference1.GetMentorRequest inValue = new EComWFE.ServiceReference1.GetMentorRequest();
            inValue.Body = new EComWFE.ServiceReference1.GetMentorRequestBody();
            EComWFE.ServiceReference1.GetMentorResponse retVal = ((EComWFE.ServiceReference1.HelloServiceSoap)(this)).GetMentor(inValue);
            return retVal.Body.GetMentorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EComWFE.ServiceReference1.GetMentorResponse> EComWFE.ServiceReference1.HelloServiceSoap.GetMentorAsync(EComWFE.ServiceReference1.GetMentorRequest request) {
            return base.Channel.GetMentorAsync(request);
        }
        
        public System.Threading.Tasks.Task<EComWFE.ServiceReference1.GetMentorResponse> GetMentorAsync() {
            EComWFE.ServiceReference1.GetMentorRequest inValue = new EComWFE.ServiceReference1.GetMentorRequest();
            inValue.Body = new EComWFE.ServiceReference1.GetMentorRequestBody();
            return ((EComWFE.ServiceReference1.HelloServiceSoap)(this)).GetMentorAsync(inValue);
        }
        
        public System.DateTime GetNextTestDay() {
            return base.Channel.GetNextTestDay();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> GetNextTestDayAsync() {
            return base.Channel.GetNextTestDayAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EComWFE.ServiceReference1.ValidateResponse EComWFE.ServiceReference1.HelloServiceSoap.Validate(EComWFE.ServiceReference1.ValidateRequest request) {
            return base.Channel.Validate(request);
        }
        
        public bool Validate(string userName, string password) {
            EComWFE.ServiceReference1.ValidateRequest inValue = new EComWFE.ServiceReference1.ValidateRequest();
            inValue.Body = new EComWFE.ServiceReference1.ValidateRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            EComWFE.ServiceReference1.ValidateResponse retVal = ((EComWFE.ServiceReference1.HelloServiceSoap)(this)).Validate(inValue);
            return retVal.Body.ValidateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EComWFE.ServiceReference1.ValidateResponse> EComWFE.ServiceReference1.HelloServiceSoap.ValidateAsync(EComWFE.ServiceReference1.ValidateRequest request) {
            return base.Channel.ValidateAsync(request);
        }
        
        public System.Threading.Tasks.Task<EComWFE.ServiceReference1.ValidateResponse> ValidateAsync(string userName, string password) {
            EComWFE.ServiceReference1.ValidateRequest inValue = new EComWFE.ServiceReference1.ValidateRequest();
            inValue.Body = new EComWFE.ServiceReference1.ValidateRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((EComWFE.ServiceReference1.HelloServiceSoap)(this)).ValidateAsync(inValue);
        }
    }
}
